version: '3'

services:
  php:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: movies_laravel_php
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated

  nginx:
    image: nginx:1.17-alpine
    container_name: movies_laravel_nginx
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

networks:
  default:
    external:
      name: reverse-proxy
